# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
target 'codefest' do
        use_frameworks!
        # Pods for codefest
        pod 'GoogleMaps', '4.1.0'
        pod 'GooglePlaces', '4.1.0'
end
