# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
target 'codefest' do
        use_frameworks!
        # Pods for codefest
        pod 'GoogleMaps', '4.1.0'
        pod 'GooglePlaces', '4.1.0'
        #pods for firebase
        # add the Firebase pod for Google Analytics
        pod 'Firebase/Analytics'
        # add pods for any other desired Firebase products
        
        # Add the pods for any other Firebase products you want to use in your app
        # For example, to use Firebase Authentication and Cloud Firestore
        pod 'Firebase/Auth'
        pod 'Firebase/Firestore'
        pod 'SwiftyJSON', '5.0'
        pod 'Alamofire', '5.4'
        pod 'Firebase/Database'
        #https://firebase.google.com/docs/ios/setup#available-pods
end
