# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codefest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'GoogleMaps'
    pod 'GooglePlaces' 
  # Pods for codefest

  target 'codefestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'codefestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
